### ISSUE TITLE
Contributors wanted for Hacktoberfest 2021

### ISSUE THREAD

**Issue by MazontheMoon** [MazontheMoon/myhacktoberfest2021tribute#2]
This project is aimed for beginner or newbie frontend devs who want to participate in Hacktoberfest but struggle to find a project to contribute to within their skillset. This project requires only knowledge of CSS and HTML ... and github of course! See contributing.md for guidelines

**Comment by nishant-giri** [comment]
@suyalamritanshu, can I contribute in this project?

**Comment by suyalamritanshu** [comment]
sure @nishant-giri

**Comment by yamini3707** [comment]
Please assign me this.

**Comment by suyalamritanshu** [comment]
@yamini3707 sure

**Comment by wal33dahmad** [comment]
Can I contribute to this project?

**Comment by wal33dahmad** [comment]
@MazontheMoon plz do approve my PR for hacktoberfest. Heres the link: https://github.com/MazontheMoon/myhacktoberfest2021tribute/pull/9

**Comment by yamini3707** [comment]
> @yamini3707 sure

Hey, I have made some changes. Apart from adding some cards, I also changed the style of web page. If you don't like it and want some changes let me know I will edit it. Thank You.

**Comment by Yash-RajSingh** [comment]
Hey! i too, would like to contribute in this. Can you please assign this to me?

**Comment by MazontheMoon** [comment]
Hi,
Please check out CONTRIBUTING for guidelines and go ahead to add your own
card.

**Comment by MazontheMoon** [comment]
Hi, I can't see any PR from you with your changes?
